apiVersion: apps/v1
kind: Deployment
metadata:
  name: colaborare-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: colaborare
  template:
    metadata:
      labels:
        app: colaborare
    spec:
      containers:
        - name: colaborare
          image: george1999/colaborare
          env:
            - name: jwt
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: jwt
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: licenta
---
apiVersion: v1
kind: Service
metadata:
  name: colaborare-service
spec:
  selector:
    app: colaborare
  ports:
    - name: colaborare
      protocol: TCP
      port: 3503
      targetPort: 3503
